/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as ApiCampaignRouteImport } from './routes/api/campaign'
import { Route as ApiClaimRouteImport } from './routes/api/claim'
import { Route as ApiEditCampaignRouteImport } from './routes/api/edit-campaign'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiImpressionRouteImport } from './routes/api/impression'
import { Route as ApiLearnRouteImport } from './routes/api/learn'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiResultsRouteImport } from './routes/api/results'
import { Route as ApiRunAgentRouteImport } from './routes/api/run-agent'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignRoute = ApiCampaignRouteImport.update({
  id: '/api/campaign',
  path: '/api/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimRoute = ApiClaimRouteImport.update({
  id: '/api/claim',
  path: '/api/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditCampaignRoute = ApiEditCampaignRouteImport.update({
  id: '/api/edit-campaign',
  path: '/api/edit-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpressionRoute = ApiImpressionRouteImport.update({
  id: '/api/impression',
  path: '/api/impression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnRoute = ApiLearnRouteImport.update({
  id: '/api/learn',
  path: '/api/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsRoute = ApiResultsRouteImport.update({
  id: '/api/results',
  path: '/api/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunAgentRoute = ApiRunAgentRouteImport.update({
  id: '/api/run-agent',
  path: '/api/run-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/api/campaign': typeof ApiCampaignRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/edit-campaign': typeof ApiEditCampaignRoute
  '/api/health': typeof ApiHealthRoute
  '/api/impression': typeof ApiImpressionRoute
  '/api/learn': typeof ApiLearnRoute
  '/api/reset': typeof ApiResetRoute
  '/api/results': typeof ApiResultsRoute
  '/api/run-agent': typeof ApiRunAgentRoute
  '/api/state': typeof ApiStateRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/api/campaign': typeof ApiCampaignRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/edit-campaign': typeof ApiEditCampaignRoute
  '/api/health': typeof ApiHealthRoute
  '/api/impression': typeof ApiImpressionRoute
  '/api/learn': typeof ApiLearnRoute
  '/api/reset': typeof ApiResetRoute
  '/api/results': typeof ApiResultsRoute
  '/api/run-agent': typeof ApiRunAgentRoute
  '/api/state': typeof ApiStateRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offer': typeof OfferRoute
  '/api/campaign': typeof ApiCampaignRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/edit-campaign': typeof ApiEditCampaignRoute
  '/api/health': typeof ApiHealthRoute
  '/api/impression': typeof ApiImpressionRoute
  '/api/learn': typeof ApiLearnRoute
  '/api/reset': typeof ApiResetRoute
  '/api/results': typeof ApiResultsRoute
  '/api/run-agent': typeof ApiRunAgentRoute
  '/api/state': typeof ApiStateRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offer'
    | '/api/campaign'
    | '/api/claim'
    | '/api/edit-campaign'
    | '/api/health'
    | '/api/impression'
    | '/api/learn'
    | '/api/reset'
    | '/api/results'
    | '/api/run-agent'
    | '/api/state'
    | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offer'
    | '/api/campaign'
    | '/api/claim'
    | '/api/edit-campaign'
    | '/api/health'
    | '/api/impression'
    | '/api/learn'
    | '/api/reset'
    | '/api/results'
    | '/api/run-agent'
    | '/api/state'
    | '/api/voice'
  id:
    | '__root__'
    | '/'
    | '/offer'
    | '/api/campaign'
    | '/api/claim'
    | '/api/edit-campaign'
    | '/api/health'
    | '/api/impression'
    | '/api/learn'
    | '/api/reset'
    | '/api/results'
    | '/api/run-agent'
    | '/api/state'
    | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfferRoute: typeof OfferRoute
  ApiCampaignRoute: typeof ApiCampaignRoute
  ApiClaimRoute: typeof ApiClaimRoute
  ApiEditCampaignRoute: typeof ApiEditCampaignRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImpressionRoute: typeof ApiImpressionRoute
  ApiLearnRoute: typeof ApiLearnRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiResultsRoute: typeof ApiResultsRoute
  ApiRunAgentRoute: typeof ApiRunAgentRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaign': {
      id: '/api/campaign'
      path: '/api/campaign'
      fullPath: '/api/campaign'
      preLoaderRoute: typeof ApiCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim': {
      id: '/api/claim'
      path: '/api/claim'
      fullPath: '/api/claim'
      preLoaderRoute: typeof ApiClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-campaign': {
      id: '/api/edit-campaign'
      path: '/api/edit-campaign'
      fullPath: '/api/edit-campaign'
      preLoaderRoute: typeof ApiEditCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impression': {
      id: '/api/impression'
      path: '/api/impression'
      fullPath: '/api/impression'
      preLoaderRoute: typeof ApiImpressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn': {
      id: '/api/learn'
      path: '/api/learn'
      fullPath: '/api/learn'
      preLoaderRoute: typeof ApiLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results': {
      id: '/api/results'
      path: '/api/results'
      fullPath: '/api/results'
      preLoaderRoute: typeof ApiResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-agent': {
      id: '/api/run-agent'
      path: '/api/run-agent'
      fullPath: '/api/run-agent'
      preLoaderRoute: typeof ApiRunAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfferRoute: OfferRoute,
  ApiCampaignRoute: ApiCampaignRoute,
  ApiClaimRoute: ApiClaimRoute,
  ApiEditCampaignRoute: ApiEditCampaignRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImpressionRoute: ApiImpressionRoute,
  ApiLearnRoute: ApiLearnRoute,
  ApiResetRoute: ApiResetRoute,
  ApiResultsRoute: ApiResultsRoute,
  ApiRunAgentRoute: ApiRunAgentRoute,
  ApiStateRoute: ApiStateRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
